version: "3.9"
services:
    game_server:
        image: lugobots/server:${SERVER_VERSION:-latest}
        command: play --dev-mode --timer-mode=wait
        ports:
            - "5000:5000"
            - "8080:8080"
        healthcheck:
            test: ["CMD", "grpc-health-probe", "-addr=game_server:5000"]
            interval: 2s
            timeout: 5s
            retries: 100
            start_period: 10s
    player_01:
        image: node:18
        working_dir: /app
        command: npm run start
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - "./:/app"
        network_mode: "host"
        environment:
            - BOT_NUMBER=1
            - BOT_TEAM=home
            - TRY_CATCH_BALL=${TRY_CATCH_BALL}
            - MOVE_IN_BALL_DIRECTION=${MOVE_IN_BALL_DIRECTION}
            - MOVE_TO_EXPECTED_POSITION=${MOVE_TO_EXPECTED_POSITION}
    player_02:
        image: node:18
        working_dir: /app
        command: npm run start
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - "./:/app"
        network_mode: "host"
        environment:
            - BOT_NUMBER=2
            - BOT_TEAM=home
            - TRY_CATCH_BALL=${TRY_CATCH_BALL}
            - MOVE_IN_BALL_DIRECTION=${MOVE_IN_BALL_DIRECTION}
            - MOVE_TO_EXPECTED_POSITION=${MOVE_TO_EXPECTED_POSITION}
    player_03:
        image: node:18
        working_dir: /app
        command: npm run start
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - "./:/app"
        network_mode: "host"
        environment:
            - BOT_NUMBER=3
            - BOT_TEAM=home
            - TRY_CATCH_BALL=${TRY_CATCH_BALL}
            - MOVE_IN_BALL_DIRECTION=${MOVE_IN_BALL_DIRECTION}
            - MOVE_TO_EXPECTED_POSITION=${MOVE_TO_EXPECTED_POSITION}
    player_04:
        image: node:18
        working_dir: /app
        command: npm run start
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - "./:/app"
        network_mode: "host"
        environment:
            - BOT_NUMBER=4
            - BOT_TEAM=home
            - TRY_CATCH_BALL=${TRY_CATCH_BALL}
            - MOVE_IN_BALL_DIRECTION=${MOVE_IN_BALL_DIRECTION}
            - MOVE_TO_EXPECTED_POSITION=${MOVE_TO_EXPECTED_POSITION}
    player_05:
        image: node:18
        working_dir: /app
        command: npm run start
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - "./:/app"
        network_mode: "host"
        environment:
            - BOT_NUMBER=5
            - BOT_TEAM=home
            - TRY_CATCH_BALL=${TRY_CATCH_BALL}
            - MOVE_IN_BALL_DIRECTION=${MOVE_IN_BALL_DIRECTION}
            - MOVE_TO_EXPECTED_POSITION=${MOVE_TO_EXPECTED_POSITION}
    player_06:
        image: node:18
        working_dir: /app
        command: npm run start
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - "./:/app"
        network_mode: "host"
        environment:
            - BOT_NUMBER=6
            - BOT_TEAM=home
            - TRY_CATCH_BALL=${TRY_CATCH_BALL}
            - MOVE_IN_BALL_DIRECTION=${MOVE_IN_BALL_DIRECTION}
            - MOVE_TO_EXPECTED_POSITION=${MOVE_TO_EXPECTED_POSITION}
    player_07:
        image: node:18
        working_dir: /app
        command: npm run start
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - "./:/app"
        network_mode: "host"
        environment:
            - BOT_NUMBER=7
            - BOT_TEAM=home
            - TRY_CATCH_BALL=${TRY_CATCH_BALL}
            - MOVE_IN_BALL_DIRECTION=${MOVE_IN_BALL_DIRECTION}
            - MOVE_TO_EXPECTED_POSITION=${MOVE_TO_EXPECTED_POSITION}
    player_08:
        image: node:18
        working_dir: /app
        command: npm run start
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - "./:/app"
        network_mode: "host"
        environment:
            - BOT_NUMBER=8
            - BOT_TEAM=home
            - TRY_CATCH_BALL=${TRY_CATCH_BALL}
            - MOVE_IN_BALL_DIRECTION=${MOVE_IN_BALL_DIRECTION}
            - MOVE_TO_EXPECTED_POSITION=${MOVE_TO_EXPECTED_POSITION}
    player_09:
        image: node:18
        working_dir: /app
        command: npm run start
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - "./:/app"
        network_mode: "host"
        environment:
            - BOT_NUMBER=9
            - BOT_TEAM=home
            - TRY_CATCH_BALL=${TRY_CATCH_BALL}
            - MOVE_IN_BALL_DIRECTION=${MOVE_IN_BALL_DIRECTION}
            - MOVE_TO_EXPECTED_POSITION=${MOVE_TO_EXPECTED_POSITION}
    player_10:
        image: node:18
        working_dir: /app
        command: npm run start
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - "./:/app"
        network_mode: "host"
        environment:
            - BOT_NUMBER=10
            - BOT_TEAM=home
            - TRY_CATCH_BALL=${TRY_CATCH_BALL}
            - MOVE_IN_BALL_DIRECTION=${MOVE_IN_BALL_DIRECTION}
            - MOVE_TO_EXPECTED_POSITION=${MOVE_TO_EXPECTED_POSITION}
    player_11:
        image: node:18
        working_dir: /app
        command: npm run start
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - "./:/app"
        network_mode: "host"
        environment:
            - BOT_NUMBER=11
            - BOT_TEAM=home
            - TRY_CATCH_BALL=${TRY_CATCH_BALL}
            - MOVE_IN_BALL_DIRECTION=${MOVE_IN_BALL_DIRECTION}
            - MOVE_TO_EXPECTED_POSITION=${MOVE_TO_EXPECTED_POSITION}
    player_away_01:
        image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
        network_mode: "host"
        environment:
            - BOT_NUMBER=1
            - BOT_TEAM=away
        depends_on:
            game_server:
                condition: service_healthy
    player_away_02:
        image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
        network_mode: "host"
        environment:
            - BOT_NUMBER=2
            - BOT_TEAM=away
        depends_on:
            game_server:
                condition: service_healthy
    player_away_03:
        image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
        network_mode: "host"
        environment:
            - BOT_NUMBER=3
            - BOT_TEAM=away
        depends_on:
            game_server:
                condition: service_healthy
    player_away_04:
        image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
        network_mode: "host"
        environment:
            - BOT_NUMBER=4
            - BOT_TEAM=away
        depends_on:
            game_server:
                condition: service_healthy
    player_away_05:
        image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
        network_mode: "host"
        environment:
            - BOT_NUMBER=5
            - BOT_TEAM=away
        depends_on:
            game_server:
                condition: service_healthy
    player_away_06:
        image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
        network_mode: "host"
        environment:
            - BOT_NUMBER=6
            - BOT_TEAM=away
        depends_on:
            game_server:
                condition: service_healthy
    player_away_07:
        image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
        network_mode: "host"
        environment:
            - BOT_NUMBER=7
            - BOT_TEAM=away
        depends_on:
            game_server:
                condition: service_healthy
    player_away_08:
        image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
        network_mode: "host"
        environment:
            - BOT_NUMBER=8
            - BOT_TEAM=away
        depends_on:
            game_server:
                condition: service_healthy
    player_away_09:
        image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
        network_mode: "host"
        environment:
            - BOT_NUMBER=9
            - BOT_TEAM=away
        depends_on:
            game_server:
                condition: service_healthy
    player_away_10:
        image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
        network_mode: "host"
        environment:
            - BOT_NUMBER=10
            - BOT_TEAM=away
        depends_on:
            game_server:
                condition: service_healthy
    player_away_11:
        image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
        network_mode: "host"
        environment:
            - BOT_NUMBER=11
            - BOT_TEAM=away
        depends_on:
            game_server:
                condition: service_healthy
